title = 'Mother-to-be-journey'

contentDir = 'content/en'
languageName = 'English'
languageCode = 'en-US'

copyright = 'All rights reserved'

weight = 2

[params]
    author = 'Hao Pham'
    description = ''